# --- Defaults ---

# --- pymarl options, 这些参数有可能不环境和算法的重复配置覆盖掉 ---
runner: "episode" # 运行1个env，如果是parallel是并发运行多个env
mac: "basic_mac" # Basic controller
env: "sc2" # env的名字，sc2是星际争霸2, 'stag_hunt'是捕猎者游戏
env_args: {} # env的一些参数
batch_size_run: 1 # 并发运行的环境数量
test_nepisode: 20 # 测试的episode量
test_interval: 2000 # 多少个timeSteps之后开始测试
test_greedy: True # 使用贪婪评估（如果是False，将epsilon设置为0)
log_interval: 2000 # 每个{}时间步后记录统计数据日志
runner_log_interval: 2000 #每个{}时间步来记录runner stats（不是测试统计数据）
learner_log_interval: 2000 # 每个{} timesteps的记录训练统计信息
t_max: 10000 # 在这个时间下停止运行
use_cuda: True # 默认情况下使用GPU，除非它不可用
buffer_cpu_only: True # 如果是True，我们就不会把所有的回放缓冲区都保留在vram中。

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: False # Save the models to disk
save_model_interval: 2000000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"

run: "default"
