# --- Defaults for 4x4 predator prey, 4 agent capture, walls ---

env: "stag_hunt"

env_args:
    map_name: "stag_hunt"
    capture_action: True
    n_agents: 8   #多少个猎人
    n_stags: 8   # 多少头鹿
    n_hare: 0    #多少个野兔
    miscapture_punishment: 0
    agent_obs: [2, 2]       # (半径-1）的agent的观察，例如，[0，0]
    agent_move_block: [0,1,2]   #agent的行动被哪些实体阻止（0=agent，1=stags，2=hare）
#    capture_action: False   # 捕获是否需要额外的动作（true）或只是capture_conditions（false)
    capture_conditions: [0, 1]  # 捕获[stag, hare]可用的自由fields数量
    capture_action_conditions: [2, 1]  # 必须同时执行“捕获”动作的agent数量
    capture_freezes: True   # 捕获任何猎物是否会冻结参与的agent（True）或不（False)
    capture_terminal: False # 是否捕获任何猎物结束episode
    directed_observations: False   # agent观察他们周围的square（False）或最后行动方向的cone圆锥体（True）。
    directed_cone_narrow: True     # 是否从指向的观察cone中排除了对角线（true）
    directed_exta_actions: True    # observation cone是否由运动（False）或行动（True）控制
    episode_limit: 200      # 每个episode的最大时间steps
    intersection_global_view: False # 特定交叉(MACKRL)
    intersection_unknown: False     # intersection specific (MACKRL)
#    miscapture_punishment: -1       # 如果少于Capture_Action_Conditions agent执行Capture_Action，则处罚
    mountain_slope: 0.0     # 不执行 "向上 "动作的概率（stag_hunt = 0.0）
    mountain_spawn: False   # 猎物是否在他们的首选栖息地（True）或随机（False）
    mountain_agent_row: -1  # spawned agent的行（0为顶）。负值表示会随机产生agent。
#    n_agents: 2             # 捕猎人数 , i.e., agents
#    n_hare: 2               # 环境中的野兔数量
#    n_stags: 1              # 环境中的鹿数量
    observe_state: False    # 观察是否只是部分的（False）或包括agent位置的中心（True）。
    observe_walls: False    # 将墙壁视为额外的特征（仅适用于state_as_list = False和toroidal = False）
    observe_ids: False      # 观察agent ID，而不是agent存在（仅用于state_as_list = False）
    observe_one_hot: False  # 观察agentID作为one-hot量向量（仅适用于observer_ids = True）
    p_stags_rest: 0.0       # 雄鹿不会移动的概率（每个时间步）
    p_hare_rest: 0.0        # 野兔不会移动的概率（每个时间步）
    prevent_cannibalism: True   # 如果设置为False，猎物可以被其他猎物捕获（witch是有奖励的）。
    print_caught_prey: False    # 打印有关捕获猎物和完成episode的调试消息
    print_frozen_agents: False  # 在捕获一些猎物后，有关冻结agent的调试消息
    random_ghosts: False    # 如果是 "True"，猎物会随机变成幽灵（否定的奖励），由一个角落的特征来表示
    random_ghosts_prob: 0.5 # 猎物变成幽灵的概率
    random_ghosts_mul: -1   # 捕捉幽灵会引发奖励/惩罚random_ghost_mul *reward
    random_ghosts_indicator: False  # 如果是真的，ghost的指标每个episode都在不同的角落。
    remove_frozen: True     # 冻结的agent是否被移除（True）或仍然存在于世界中（False）。
    reward_hare: 1          # 捕获野兔的奖励
    reward_stag: 10         # 捕获雄鹿的奖励
    reward_collision: 0     # 与其他agent碰撞的奖励（或惩罚）
    reward_time: 0          # 每个时间步的奖励（或惩罚）
    state_as_graph: False   # 状态是一个实体的列表（True）还是整个网格（False）。
    toroidal: False         # 世界是否有界（False）或环形(True）
    world_shape: [10, 10]   # 网格世界的形状[高度，宽度]

test_greedy: True
test_nepisode: 16
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
obs_agent_id: False
